name: drone_detection
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.12.1=pyhcf101f3_0
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=1.3.2=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - liblzma=5.8.2=hb03c661_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh8b19718_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-gil=3.10.19=hd8ed1ab_2
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_ha0e22de_103
  - torchtriton=3.1.0=py310
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer-slim=0.21.1=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - ipython==8.38.0
    - pyarrow==23.0.0
    - scipy==1.15.3
    - torch==2.10.0+cu130
    - torchvision==0.25.0+cu130

prefix: "/home/smonzon/.local/share/mamba/envs/drone_detection"
